# An OpenAPI 3 definition of the Flat API
#
# This is used for generating API documentation and the types used by the API clients.
#
# Some style notes:
# - This file is used by ReDoc, which allows GitHub Flavored Markdown in descriptions.
# - There is no maximum line length, for ease of editing and pretty diffs.
openapi: 3.0.3
info:
  title: Flat API
  description: |
    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:

    * Creating and importing new music scores using MusicXML, MIDI, Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar and MuseScore files
    * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI)
    * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.

    The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body.
    The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/).
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).

    You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).

    Getting Started and learn more:

    * [API Overview and introduction](https://flat.io/developers/docs/api/)
    * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html)
    * [SDKs](https://flat.io/developers/docs/api/sdks.html)
    * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html)
    * [Changelog](https://flat.io/developers/docs/api/changelog.html)
  termsOfService: https://flat.io/legal
  contact:
    name: Flat
    url: https://flat.io/developers/docs/api/
    email: developers@flat.io
  version: 2.21.0
  x-logo:
    url: https://prod.flat-cdn.com/img/logo-flat.svg
servers:
- url: https://api.flat.io/v2
tags:
- name: Account
  description: |
    These API endpoints are related to the Flat account you are currently using. When using an OAuth2 access token, you can use [`GET /me`](#operation/getAuthenticatedUser) to get information about the account.
  x-displayName: Accounts
- name: Score
  description: |
    Sheet music is the main API object type available for all Flat account.
    Here is a typical lifecycle for a music score document on Flat:
      - An end user can **create a music score** or **import a document** using our [web interface](https://flat.io) or a third-party website/app (e.g. Google Drive) using this API (see [`POST /v2/scores`](#operation/createScore). The creation and import of music scores can be done with this single API endpoint. This one currently supports the [MusicXML](http://www.musicxml.com/) (compressed or not) and [MIDI](https://www.midi.org/specifications).
      - **List scores**:
        - The **owned scores** can be listed using the [collections API methods](#tag/Collection), especially [`GET /collections/{collection}/scores`](#operation/listCollectionScores).
        - The scores from a public account can be listed with [`GET /users/{user}/scores`](#operation/getUserScores).
        - Scores shared with a specific group can be listed with [`GET /groups/{group}/scores`](#operation/getGroupScores).
      - The metadata of a single score can be retrieved with [`GET /scores/{score}`](#operation/getScore).
      - Scores on Flat have **one or multiple revisions**: creating a new score will create a first revision. These **revisions can be listed** using [`GET /scores/{score}/revisions`](#operation/getScoreRevisions) and a specific **revision data can be downloaded** with [`GET /scores/{score}/revisions/{revision}/{format}`](#operation/getScoreRevisionData). New revisions can be created using our [sheet music editor](https://flat.io) or using [`POST /scores/{score}/revisions`](#operation/createScor[...]
      - Scores can be **shared publicly** by changing the privacy option with [`POST /scores/{score}`](#operation/editScore), or **individually shared** using the different collaborators API endpoints (see [`POST /scores/{score}/collaborators`](#operation/addScoreCollaborator)).
  x-displayName: Music scores
- name: Collection
  description: |
    Collections let you organize your content in a Flat account. They work like a regular _folder_ with some specificities:
      - Our design goal here is to create a system similar to a _book_ or a _playlist of songs_.
      - Collections can't have children collections (except the `trash` and `sharedWithMe` that are special collections).
      - Any score can be added to one or multiple collections. For example, you can have a single private score in two or more collections, or add any public or shared scores to one of your collections.

    All the collections don't have the same capabilities. Capabilities depend on the `type` of collection and the `rights` you have on a collection. They are available when [listing the collection](#operation/listCollections) or [retrieving the collection details](#operation/getCollection).

    By default, when using an OAuth2 access token or a personal token, all the new scores will be added to a dedicated app collection created in the user account.
    This collection has an alias `app`. For example, you can use `GET /v2/collections/app/scores` to list all the scores created by your app.

    At this time, only `private` privacy mode is widely available. Privacy modes `public`, `organizationPublic` and `privateLink`, and 1:1 sharing will be available in an upcoming update later this year.
  x-displayName: Collections of music scores
- name: User
  x-displayName: Users profiles
  description: API methods related to the Flat Community user profiles and Flat for Education profiles
- name: Organization
  x-displayName: Flat for Education Organizations
  description: Flat for Education Organizations
- name: Class
  x-displayName: Flat for Education Classes
  description: Flat for Education Classes
- name: EduResources
  x-displayName: Flat for Education Resources [Beta]
  description: |
    Resource libraries in Flat for Education.
    These API endpoints are in beta and may include breaking changes over the upcoming months.
- name: Group
  x-displayName: Flat for Education Groups
  description: Flat for Education Groups
- name: Task
  x-displayName: Asynchronous tasks
  description: Scheduled and asynchronous tasks
paths:
  /me:
    get:
      tags:
      - Account
      summary: Get current user account
      description: |
        Get details about the current authenticated User.
      operationId: getAuthenticatedUser
      security:
      - OAuth2:
        - account.public_profile
        - account.education_profile
  /scores:
    post:
      tags:
      - Score
      summary: Create a new score
      description: |
        Use this API method to **create a new music score in the current User account**. This API endpoints provides 3 ways to create scores:

        * `ScoreCreationBuilderData` : Create a blank score by providing the list of instruments to use. You can optionally customize the initial key signature, time signature, enable TABs, Chord grids, as well as the page layout.
        * `ScoreCreationFileImport`: Import an existing MusicXML 3 file (`vnd.recordare.musicxml` or `vnd.recordare.musicxml+xml`), a MIDI file (`audio/midi`), Guitar Pro (GP3, GP4, GP5, GPX, GP), PowerTab, TuxGuitar, or MuseScore file to create the new Flat document.
        * `ScoreCreationGoogleDriveImport`: Import an existing Google Drive file from the connected Google Drive account.

        This API call will automatically create the first revision of the document, the score can be modified by the using our web application or by uploading a new revision of this file (`POST /v2/scores/{score}/revisions/{revision}`).

        The currently authenticated user will be granted owner of the file and will be able to add other collaborators (users and groups).

        If no `collection` is specified, the API will create the score in the most appropriate collection. When using an OAuth2 access token or a personal token, the score will be automatically added to your dedicated app collection in the account (`/v2/collections/app`).

        If a `collection` is specified and this one has more public privacy settings than the score (e.g. `public` vs `private` for the score), the privacy settings of the created score will be adjusted to the collection ones.

        You can check the adjusted privacy settings in the returned score `privacy`, and optionally adjust these settings if needed using `PUT /scores/{score}`.
      operationId: createScore
      security:
      - OAuth2:
        - scores
  /scores/{score}:
    get:
      tags:
      - Score
      summary: Get a score's metadata
      description: |
        Get the details of a score identified by the `score` parameter in the URL.
        The currently authenticated user must have at least a read access to the document to use this API call.
      operationId: getScore
      security:
      - OAuth2:
        - scores
        - scores.readonly
    put:
      tags:
      - Score
      summary: Edit a score's metadata
      description: |
        This API method allows you to change the metadata of a score document (e.g. its `title` or `privacy`), all the properties are optional.

        To edit the file itself, create a new revision using the appropriate method (`POST /v2/scores/{score}/revisions/{revision}`).

        When editing the `title`, `subtitle`, `composer`, `lyricist`, `arranger` or `licenseText`, the metadatas will be instantly be updated, and a real-time action will be pushed to update the document lazily.
        This pending document modification will be automatically be saved as a new version by either a connected client or our internal versioning service.
      operationId: editScore
      security:
      - OAuth2:
        - scores
    delete:
      tags:
      - Score
      summary: Delete a score
      description: |
        This method can be used by anyone that has at least read access to the document:

        - When called by an owner/admin, it will schedule the deletion of the score, its revisions, and complete history. The score won't be accessible anymore after calling this method and the user's quota will directly be updated.
        - When called by a collaborator, the score will be unshared (i.e. removed from the account & own collections).
        - When called by another user that has the score in its collections, the score will be removed from all the user collections.
      operationId: deleteScore
      security:
      - OAuth2:
        - scores
  /scores/{score}/untrash:
    post:
      tags:
      - Score
      summary: Untrash a score
      description: |
        This method will remove the score from the `trash` collection and from the deletion queue, and add it back to the original collections.
      operationId: untrashScore
      security:
      - OAuth2:
        - scores
  /scores/{score}/submissions:
    get:
      tags:
      - Score
      - Class
      summary: List submissions related to the score
      description: |
        This API call will list the different assignments submissions where the score is attached. This method can be used by anyone that are part of the organization and have at least read access to the document.
      operationId: getScoreSubmissions
      security:
      - OAuth2:
        - scores
        - scores.readonly
  /scores/{score}/fork:
    post:
      tags:
      - Score
      summary: Fork a score
      description: |
        This API call will make a copy of the last revision of the specified score and create a new score. The copy of the score will have a privacy set to `private`.

        When using a [Flat for Education](https://flat.io/edu) account, the inline and contextualized comments will be accessible in the child document.
      operationId: forkScore
      security:
      - OAuth2:
        - scores
  /scores/{score}/collaborators:
    get:
      tags:
      - Score
      summary: List the collaborators
      description: |
        This API call will list the different collaborators of a score and their rights on the document. The returned list will at least contain the owner of the document.

        Collaborators can be a single user (the object `user` will be populated) or a group (the object `group` will be populated).
      operationId: getScoreCollaborators
      security:
      - OAuth2:
        - scores.readonly
        - scores
    post:
      tags:
      - Score
      summary: Add a new collaborator
      description: |
        Share a score with a single user or a group. This API call allows to add, invite and update the collaborators of a resource.
        - To add an existing Flat user to the resource, specify its unique identifier in the `user` property.
        - To invite an external user to the resource, specify its email in the `userEmail` property.
        - To add a Flat group to the resource, specify its unique identifier in the `group` property.
        - To update an existing collaborator, process the same request with different rights.
      operationId: addScoreCollaborator
      security:
      - OAuth2:
        - scores
  /scores/{score}/collaborators/{collaborator}:
    get:
      tags:
      - Score
      summary: Get a collaborator
      description: |
        Get the information about a collaborator (User or Group).
      operationId: getScoreCollaborator
      security:
      - OAuth2:
        - scores.readonly
    delete:
      tags:
      - Score
      summary: Delete a collaborator
      description: |
        Remove the specified collaborator from the score
      operationId: removeScoreCollaborator
      security:
      - OAuth2:
        - scores
  /scores/{score}/tracks:
    get:
      tags:
      - Score
      summary: List the audio or video tracks linked to a score
      operationId: listScoreTracks
      security:
      - OAuth2:
        - scores
        - scores.readonly
    post:
      tags:
      - Score
      summary: Add a new video or audio track to the score
      description: |
        Use this method to add new track to the score. This track can then be played on flat.io or in an embedded score.
        This API method support medias hosted on SoundCloud, YouTube and Vimeo.
      operationId: addScoreTrack
      security:
      - OAuth2:
        - scores
  /scores/{score}/tracks/{track}:
    get:
      tags:
      - Score
      summary: Retrieve the details of an audio or video track linked to a score
      operationId: getScoreTrack
      security:
      - OAuth2:
        - scores
        - scores.readonly
    put:
      tags:
      - Score
      summary: Update an audio or video track linked to a score
      operationId: updateScoreTrack
      security:
      - OAuth2:
        - scores
    delete:
      tags:
      - Score
      summary: Remove an audio or video track linked to the score
      operationId: deleteScoreTrack
      security:
      - OAuth2:
        - scores
  /scores/{score}/comments:
    get:
      tags:
      - Score
      summary: List comments
      description: This method lists the different comments added on a music score (documents and inline) sorted by their post dates.
      operationId: getScoreComments
      security:
      - OAuth2:
        - scores.readonly
        - scores.social
        - scores
    post:
      tags:
      - Score
      summary: Post a new comment
      description: |
        Post a document or a contextualized comment on a document.

        Please note that this method includes an anti-spam system for public scores. We don't guarantee that your comments will be accepted and displayed to end-user. Comments are be blocked by returning a `403` HTTP error and hidden from other users when the `spam` property is `true`.
      operationId: postScoreComment
      security:
      - OAuth2:
        - scores.social
        - scores
  /scores/{score}/comments/{comment}:
    put:
      tags:
      - Score
      summary: Update an existing comment
      operationId: updateScoreComment
      security:
      - OAuth2:
        - scores.social
        - scores
    delete:
      tags:
      - Score
      summary: Delete a comment
      operationId: deleteScoreComment
      security:
      - OAuth2:
        - scores.social
        - scores
  /scores/{score}/comments/{comment}/resolved:
    put:
      tags:
      - Score
      summary: Mark the comment as resolved
      operationId: markScoreCommentResolved
      security:
      - OAuth2:
        - scores.social
        - scores
    delete:
      tags:
      - Score
      summary: Mark the comment as unresolved
      operationId: markScoreCommentUnresolved
      security:
      - OAuth2:
        - scores.social
        - scores
  /scores/{score}/revisions:
    get:
      tags:
      - Score
      summary: List the revisions
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to list all of them, sorted by last modification.

        Depending the plan of the account, this list can be trunked to the few last revisions.
      operationId: getScoreRevisions
      security:
      - OAuth2:
        - scores
        - scores.readonly
    post:
      tags:
      - Score
      summary: Create a new revision
      description: |
        Update a score by uploading a new revision for this one.
      operationId: createScoreRevision
      security:
      - OAuth2:
        - scores
  /scores/{score}/revisions/{revision}:
    get:
      tags:
      - Score
      summary: Get a score revision
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to get a specific
        revision metadata.
      operationId: getScoreRevision
      security:
      - OAuth2:
        - scores
        - scores.readonly
  /scores/{score}/revisions/{revision}/{format}:
    get:
      tags:
      - Score
      summary: Get a score revision data
      description: |
        Retrieve the file corresponding to a score revision (the following formats are available): Flat JSON/Adagio JSON `json`, MusicXML
        `mxl`/`xml`, MP3 `mp3`, WAV `wav`, MIDI `midi`, a tumbnail of the first page `thumbnail.png` or auto sync points `synchronizationPoints`.
      operationId: getScoreRevisionData
      security:
      - OAuth2:
        - scores
        - scores.readonly
  /scores/{score}/revisions/{revision}/{format}/task:
    post:
      tags:
      - Score
      summary: Create a new score export task
      description: |
        Some of the exports of a score takes are longer to process than a simple API requests.
        Use this endpoint to launch a new export of one score hosted on Flat.
      operationId: createExportTask
      security:
      - OAuth2:
        - scores
        - scores.readonly
  /collections:
    get:
      tags:
      - Collection
      summary: List the collections
      description: |
        Use this method to list the user's collections contained in `parent` (by default in the `root` collection).
        If no sort option is provided, the collections are sorted by `creationDate` `desc`.

        Note that this method will not include the `parent` collection in the listing.
        For example, if you need the details of the `root` collection, you can use `GET /v2/collections/root`.

        To fetch your app collection details, you can use `GET /v2/collections/app`.
      operationId: listCollections
      security:
      - OAuth2:
        - collections
        - collections.readonly
    post:
      tags:
      - Collection
      summary: Create a new collection
      description: |
        This method will create a new collection and add it to your `root` collection.
      operationId: createCollection
      security:
      - OAuth2:
        - collections
  /collections/{collection}:
    get:
      tags:
      - Collection
      summary: Get collection details
      operationId: getCollection
      security:
      - OAuth2:
        - collections
        - collections.readonly
    put:
      tags:
      - Collection
      summary: Update a collection's metadata
      operationId: editCollection
      security:
      - OAuth2:
        - collections
    delete:
      tags:
      - Collection
      summary: Delete the collection
      description: |
        This method will schedule the deletion of the collection. Until deleted, the collection will be available in the `trash`.
      operationId: deleteCollection
      security:
      - OAuth2:
        - collections
  /collections/{collection}/untrash:
    post:
      tags:
      - Collection
      summary: Untrash a collection
      description: |
        This method will restore the collection by removing it from the `trash` and add it back to the `root` collection.
      operationId: untrashCollection
      security:
      - OAuth2:
        - collections
  /collections/{collection}/scores:
    get:
      tags:
      - Collection
      summary: List the scores contained in a collection
      description: |
        Use this method to list the scores contained in a collection.
        If no sort option is provided, the scores are sorted by `modificationDate` `desc`.

        For example, to list the scores contained in your app collection, you can use `GET /v2/collections/app/scores`.
      operationId: listCollectionScores
      security:
      - OAuth2:
        - collections
  /collections/{collection}/scores/{score}:
    put:
      tags:
      - Collection
      summary: Add a score to the collection
      description: |
        This operation will add a score to a collection. The default behavior will make the score available across multiple collections.
        You must have the capability `canAddScores` on the provided `collection` to perform the action.
      operationId: addScoreToCollection
      security:
      - OAuth2:
        - collections
        - collections.add_scores
    delete:
      tags:
      - Collection
      summary: Delete a score from the collection
      description: |
        This method will delete a score from the collection. Unlike [`DELETE /scores/{score}`](#operation/deleteScore), this score will not remove the score from your account, but only from the collection.
        This can be used to *move* a score from one collection to another, or simply remove a score from one collection when this one is contained in multiple collections.
      operationId: deleteScoreFromCollection
      security:
      - OAuth2:
        - collections
  /tasks/{task}:
    get:
      tags:
      - Task
      summary: Get a task details
      description: |
        This method can be used to follow a task progression, for example while a score is being exported.
      operationId: getTask
      security:
      - OAuth2:
        - tasks.readonly
  /users/{user}:
    get:
      tags:
      - User
      summary: Get a public user profile
      description: |
        Get a profile of a Flat or Flat for Education User.
      operationId: getUser
      security:
      - OAuth2:
        - account.public_profile
        - account.education_profile
  /users/{user}/likes:
    get:
      tags:
      - User
      - Score
      summary: List liked scores
      operationId: getUserLikes
      security:
      - OAuth2:
        - account.public_profile
  /users/{user}/scores:
    get:
      tags:
      - User
      - Score
      summary: List user's scores
      description: |
        Get the list of public scores owned by a User.
        If you want to access to private scores, please use the [Collections API](#tag/Collection).
        For example `GET /v2/collections/allScores/scores` to list all recently updated scores.
      operationId: getUserScores
      security:
      - OAuth2:
        - scores
        - scores.readonly
  /organizations/users:
    get:
      tags:
      - Organization
      summary: List the organization users
      operationId: listOrganizationUsers
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
    post:
      tags:
      - Organization
      summary: Create a new user account
      operationId: createOrganizationUser
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/users/count:
    get:
      tags:
      - Organization
      summary: Count the organization users using the provided filters
      operationId: countOrgaUsers
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
  /organizations/users/{user}:
    put:
      tags:
      - Organization
      summary: Update account information
      operationId: updateOrganizationUser
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
    delete:
      tags:
      - Organization
      summary: Remove an account from Flat
      description: |
        This operation removes an account from Flat and its data, including:
        * The music scores created by this user (documents, history, comments, collaboration information)
        * Education related data (assignments and classroom information)
      operationId: removeOrganizationUser
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/users/{user}/signinLink:
    post:
      tags:
      - Organization
      summary: Create a sign in link for an organization user
      operationId: createOrganizationUserSigninLink
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/users/{user}/accessToken:
    post:
      tags:
      - Organization
      operationId: createOrganizationUserAccessToken
      summary: Create a delegated API access token for an organization user
      description: |
        This operation will create an API access token for a chosen organization user.
        This token will be valid for a limited time and can be used to access the API as the organization user.
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/invitations:
    get:
      tags:
      - Organization
      summary: List the organization invitations
      operationId: listOrganizationInvitations
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
    post:
      tags:
      - Organization
      summary: Create a new invitation to join the organization
      description: |
        This method creates and sends invitation for teachers and admins.

        Invitations can only be used by new Flat users or users who are not part of the organization yet.

        If the email of the user is already associated to a user of your organization, the API will simply update the role of the existing user and won't send an invitation. In this case, the property `usedBy` will be directly filled with the uniquer identifier of the corresponding user.
      operationId: createOrganizationInvitation
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/invitations/{invitation}:
    delete:
      tags:
      - Organization
      summary: Remove an organization invitation
      operationId: removeOrganizationInvitation
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/lti/credentials:
    get:
      tags:
      - Organization
      summary: List LTI 1.x credentials
      operationId: listLtiCredentials
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.lti
        - edu.admin.lti.readonly
    post:
      tags:
      - Organization
      summary: Create a new couple of LTI 1.x credentials
      description: |
        Flat for Education is a Certified LTI Provider. You can use these API methods to automate the creation of LTI credentials. You can read more about our LTI implementation, supported components and LTI Endpoints in our [Developer Documentation](https://flat.io/developers/docs/lti/).
      operationId: createLtiCredentials
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.lti
  /organizations/lti/credentials/{credentials}:
    delete:
      tags:
      - Organization
      summary: Revoke LTI 1.x credentials
      operationId: revokeLtiCredentials
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.lti
  /classes:
    get:
      tags:
      - Class
      summary: List the classes available for the current user
      operationId: listClasses
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
    post:
      tags:
      - Class
      summary: Create a new class
      description: |
        Classrooms on Flat allow you to create activities with assignments and post content to a specific group.

        When creating a class, Flat automatically creates two groups: one for the teachers of the course, one for the students. The creator of this class is automatically added to the teachers group.

        If the classsroom is synchronized with another application like Google Classroom, some of the meta information will automatically be updated.

        You can add users to this class using `PUT /classes/{class}/users/{user}`, they will automatically added to the group based on their role on Flat. Users can also enroll themselves to this class using `POST /classes/enroll/{enrollmentCode}` and the `enrollmentCode` returned in the `ClassDetails` response.
      operationId: createClass
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}:
    get:
      tags:
      - Class
      summary: Get the details of a single class
      operationId: getClass
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
    put:
      tags:
      - Class
      summary: Update the class
      description: |
        Update the meta information of the class
      operationId: updateClass
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/archive:
    post:
      tags:
      - Class
      summary: Archive the class
      description: |
        Mark the class as `archived`. When this course is synchronized with another app, like Google Classroom, this state will be automatically be updated.
      operationId: archiveClass
      security:
      - OAuth2:
        - edu.classes
    delete:
      tags:
      - Class
      summary: Unarchive the class
      description: |
        Mark the class as `active`. When this course is synchronized with another app, like Google Classroom, this state will be automatically be updated.
      operationId: unarchiveClass
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/activate:
    post:
      tags:
      - Class
      summary: Activate the class
      description: |
        Mark the class as `active`. This is mainly used for classes synchronized from Clever that are initially with an `inactive` state and hidden in the UI.
      operationId: activateClass
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/users/{user}:
    put:
      tags:
      - Class
      summary: Add a user to the class
      description: |
        This method can be used by a teacher of the class to enroll another Flat user into the class.

        Only users that are part of your Organization can be enrolled in a class of this same Organization.

        When enrolling a user in the class, Flat will automatically add this user to the corresponding Class group, based on this role in the Organization.
      operationId: addClassUser
      security:
      - OAuth2:
        - edu.classes
    delete:
      tags:
      - Class
      summary: Remove a user from the class
      description: |
        This method can be used by a teacher to remove a user from the class, or by a student to leave the classroom.

        Warning: Removing a user from the class will remove the associated resources, including the submissions and feedback related to these submissions.
      operationId: deleteClassUser
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/students/{user}/submissions:
    get:
      tags:
      - Class
      summary: List the submissions for a student
      description: |
        Use this method as a teacher to list all the assignment submissions sent by a student of the class
      operationId: listClassStudentSubmissions
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
  /classes/{class}/assignments:
    get:
      tags:
      - Class
      summary: Assignments listing
      operationId: listAssignments
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
    post:
      tags:
      - Class
      summary: Assignment creation
      description: |
        Use this method as a teacher to create and post a new assignment to a class.

        If the class is synchronized with Google Classroom, the assignment will be automatically posted to your Classroom course.
      operationId: createClassAssignment
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
  /classes/{class}/assignments/{assignment}/copy:
    post:
      tags:
      - Class
      summary: Copy an assignment
      description: |
        Copy an assignment to a specified class or the resource library

        For class assignments:
        - If the original assignment has a due date in the past, this new assignment will be created without a due date.
        - If the class is synchronized with an external app (e.g. Google Classroom), the copied assignment will also be posted on the external app.
      operationId: copyAssignment
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
  /classes/{class}/assignments/{assignment}/archive:
    post:
      tags:
      - Class
      summary: Archive the assignment
      description: |
        Archive the assignment
      operationId: archiveAssignment
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
    delete:
      tags:
      - Class
      summary: Unarchive the assignment.
      description: |
        Mark the assignment as `active`.
      operationId: unarchiveAssignment
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
  /classes/{class}/assignments/{assignment}/submissions:
    get:
      tags:
      - Class
      summary: List the students' submissions
      operationId: getSubmissions
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
    put:
      tags:
      - Class
      summary: Create or edit a submission
      description: |
        Use this method as a student to create, update and submit a submission related to an assignment.
        Students can only set `attachments` and `submit`.
        Teachers can use `PUT /classes/{class}/assignments/{assignment}/submissions/{submission}` to update a submission by id.
      operationId: createSubmission
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
  /classes/{class}/assignments/{assignment}/submissions/csv:
    get:
      tags:
      - Class
      summary: CSV Grades exports
      description: Export list of submissions grades to a CSV file
      operationId: exportSubmissionsReviewsAsCsv
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
  /classes/{class}/assignments/{assignment}/submissions/excel:
    get:
      tags:
      - Class
      summary: Excel Grades exports
      description: Export list of submissions grades to an Excel file
      operationId: exportSubmissionsReviewsAsExcel
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
  /classes/{class}/assignments/{assignment}/submissions/{submission}:
    get:
      tags:
      - Class
      summary: Get a student submission
      operationId: getSubmission
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
    put:
      tags:
      - Class
      summary: Edit a submission
      description: |
        Use this method as a teacher to update the different submission and give feedback.
        Teachers can only set `return`, `draftGrade` and `grade`
      operationId: editSubmission
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
    delete:
      tags:
      - Class
      summary: Reset a submission
      description: |
        Use this method as a teacher to reset a submission and allow student to start over the assignment
      operationId: deleteSubmission
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
  /classes/{class}/assignments/{assignment}/submissions/{submission}/history:
    get:
      tags:
      - Class
      operationId: getSubmissionHistory
      summary: Get the history of the submission
      description: |
        For teachers only. Returns a detailed history of the submission. This currently includes state and grade histories.
      security:
      - OAuth2:
        - edu.assignments
        - edu.assignments.readonly
  /classes/{class}/assignments/{assignment}/submissions/{submission}/comments:
    get:
      tags:
      - Class
      operationId: getSubmissionComments
      summary: List the feedback comments of a submission
      security:
      - OAuth2:
        - edu.assignments
        - edu.assignments.readonly
    post:
      tags:
      - Class
      operationId: postSubmissionComment
      summary: Add a feedback comment to a submission
      security:
      - OAuth2:
        - edu.assignments
  /classes/{class}/assignments/{assignment}/submissions/{submission}/comments/{comment}:
    put:
      tags:
      - Class
      operationId: updateSubmissionComment
      summary: Update a feedback comment to a submission
      security:
      - OAuth2:
        - edu.assignments
    delete:
      tags:
      - Class
      operationId: deleteSubmissionComment
      summary: Delete a feedback comment to a submission
      security:
      - OAuth2:
        - edu.assignments
  /classes/{class}/testStudent:
    post:
      tags:
      - Class
      summary: Create a test student account
      description: |
        Test students account can be created by teachers an admin and be used to experiment the assignments.

        - They are automatically added to the class.
        - They can be reset using this API endpoint (a new account will be created and the previous one scheduled for deletion).
        - These accounts don't use a user license.
      operationId: createTestStudentAccount
      security:
      - OAuth2:
        - edu.admin
        - edu.classes
  /classes/enroll/{enrollmentCode}:
    post:
      tags:
      - Class
      summary: Join a class
      description: |
        Use this method to join a class using an enrollment code given one of the teacher of this class. This code is also available in the `ClassDetails` returned to the teachers when creating the class or listing / fetching a specific class.

        Flat will automatically add the user to the corresponding class group based on this role in the organization.
      operationId: enrollClass
      security:
      - OAuth2:
        - edu.classes
  /groups/{group}:
    get:
      tags:
      - Group
      summary: Get group information
      operationId: getGroupDetails
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
        - edu.classes
        - edu.classes.readonly
  /groups/{group}/users:
    get:
      tags:
      - Group
      summary: List group's users
      operationId: listGroupUsers
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
        - edu.classes
        - edu.classes.readonly
  /groups/{group}/scores:
    get:
      tags:
      - Group
      - Score
      summary: List group's scores
      description: |
        Get the list of scores shared with a group.
      operationId: getGroupScores
      security:
      - OAuth2:
        - scores
        - scores.readonly
  /eduResources:
    get:
      tags:
      - EduResources
      operationId: listEduResources
      summary: List education resources in a library or folder
      security:
      - OAuth2:
        - edu.resources
        - edu.resources.readonly
        - edu.assignments
        - edu.assignments.readonly
    post:
      tags:
      - EduResources
      operationId: createEduResource
      summary: Create a new education resource
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
  /eduResources/libraries:
    get:
      tags:
      - EduResources
      operationId: listEduLibraries
      summary: List the education libraries
      security:
      - OAuth2:
        - edu.resources
        - edu.resources.readonly
        - edu.assignments
        - edu.assignments.readonly
  /eduResources/{resource}:
    get:
      tags:
      - EduResources
      operationId: getEduResource
      summary: Get an education resource
      security:
      - OAuth2:
        - edu.resources
        - edu.resources.readonly
        - edu.assignments
        - edu.assignments.readonly
    put:
      tags:
      - EduResources
      operationId: updateEduResource
      summary: Update an education resource metadata
      description: |
        Update any resources metadata (e.g. title).

        Use this method to rename education resources folders or assignments.
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
    delete:
      tags:
      - EduResources
      operationId: deleteEduResource
      summary: Delete an education resource
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
  /eduResources/{resource}/move:
    post:
      tags:
      - EduResources
      operationId: moveEduResource
      summary: Move an education resource
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
  /eduResources/{resource}/copy:
    post:
      tags:
      - EduResources
      operationId: copyEduResource
      summary: Copy an education resource to a Resource Library
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
  /eduResources/{resource}/copyToDemoClass:
    post:
      tags:
      - EduResources
      operationId: copyEduResourceToDemoClass
      summary: Copy an education assignment to a teacher demo class
      description: |
        Once a resource library can be published to a class (`Assignment.capabilities.canPublishInClass = true`),
        this endpoint can be used for the feature "View as student".

        It will ensure the teacher has a demo class, then copy the assignment to the demo class.
        You can then use `POST /classes/{class}/testStudent` to create a testing student account
        in the demo class.
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
  /eduResources/{resource}/useInClass:
    post:
      tags:
      - EduResources
      operationId: useEduResourceInClass
      summary: Use an education resource in a class
      description: |
        This endpoint will copy a resource and the underlying resources.
        The assignment will be created as a draft that can be completed with other options before publishing (e.g. due date, publication date for scheduling, etc.).
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
  /eduResources/{resource}/createLtiLink:
    post:
      tags:
      - EduResources
      operationId: createEduResourceLtiLink
      summary: Create an LTI link for an education resource
      description: |
        This endpoint will return an LTI link that can be used to launch Flat for Education.
        The link, in a context from a class, will ensure the assignment has been copied in the class.
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
  /eduResources/{resource}/assignment:
    put:
      tags:
      - EduResources
      operationId: updateEduResourceAssignment
      summary: Update an education resource assignment
      security:
      - OAuth2:
        - edu.resources
        - edu.assignments
components:
  securitySchemes:
    OAuth2:
      type: oauth2
      description: |
        OAuth 2.0 authentication for your app or. Please only request the most restrictive and needed scopes. Using some of the scopes may require an additional review from our team. The Flat API supports **authorization code** and **implicit** flows.
      flows:
        authorizationCode:
          authorizationUrl: https://flat.io/auth/oauth
          tokenUrl: https://api.flat.io/oauth/access_token
          scopes:
            account.public_profile: |
              Provides access to the basic person's public profile. Education profiles may be anonymized with this scope, you can request the scope `education_profile` to access to the a basic education account profile.
            account.email: |
              Provices access to the person's email.
            account.education_profile: |
              Provides access to the basic person's education profile and public organization information.
            scores.readonly: |
              Allows read-only access to all a user's scores. You won't need this scope to read public scores.
            scores.social: |
              Allow to post comments and like scores
            scores: |
              Full, permissive scope to access all of a user's scores.
            collections.readonly: Allow read-only access to a user's collections.
            collections.add_scores: Allow to add scores to a user's collections.
            collections: Full, permissive scope to access all of a user's collections.
            notifications.readonly: Read-only access to a user's notifications.
            edu.resources: Read-write access to the resource library.
            edu.resources.readonly: Read-only access to the resource library.
            edu.classes: Full, permissive scope to manage the classes.
            edu.classes.readonly: Read-only access to the classes.
            edu.assignments: Read-write access to the assignments and submissions.
            edu.assignments.readonly: Read-only access to the assignments and submissions.
            edu.admin: Full, permissive scope to manage all the admin of an organization.
            edu.admin.lti: Access and manage the LTI Credentials for an organization.
            edu.admin.lti.readonly: Read-only access to the LTI Credentials of an organization.
            edu.admin.users: Access and manage the users and invitations of the organization.
            edu.admin.users.readonly: Read-only access to the users and invitations of the organization.
            tasks.readonly: Read-only access to export tasks created by this account.