# A Swagger 2.0 (a.k.a. OpenAPI) definition of the Flat API
#
# This is used for generating API documentation and the types used by the API clients.
#
# Some style notes:
# - This file is used by ReDoc, which allows GitHub Flavored Markdown in
#   descriptions.
# - There is no maximum line length, for ease of editing and pretty diffs.

swagger: '2.0'

info:
  title: Flat API
  description: |
    # Introduction
    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:

       - Creating and importing new music scores using MusicXML or MIDI files
       - Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI)
       - Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.

    The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body. The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/).

    You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).

    # Beta
    Please note that this public API is currently in beta and subject to change.

    Our whole platform and apps are based on this API, however not all the endpoints are available publicly yet. Feel free to [contact us](mailto:developers@flat.io) if you have any questions, feedback or features requests.

    We don't offer any guarantees during this beta period. By using this API, you agree to update your app in a timely fashion in response to any beta-period changes that are rolled out.

    By using this API, and especially on the behalf of a user account, you must accept, respect and enforce our [Terms of Service and Privacy Policy](https://flat.io/legal).

    # Authentication
    The Flat API supports OAuth2, you can request API credentials [on our website](https://flat.io/developers). We provide two types of credentials:

      - **Account Access Tokens**: Simple access tokens that allow to try and use this API **with your own account**. This is a great solution to create private apps.
      - **OAuth2 Credentials**: If you plan to use the Flat API **on the behalf of mutliple users** or make this app public, request OAuth2 Credentials.

    <!-- ReDoc-Inject: <security-definitions> -->

    ### OAuth2 Authorization page

    The Authorization page (`https://flat.io/auth/oauth`) supports all the standard parameters from the **Authorization Code** flow ([RFC6749/4.1.1](https://tools.ietf.org/html/rfc6749#section-4.1.1)) and the **Implicit** flow ([RFC6749/4.2.1](https://tools.ietf.org/html/rfc6749#section-4.2.1)). Here is a summary of the parameters available, including non-standard and optional parameters. All of them can be passed as query string when redirecting the end-user to the authorization page.

    Property name  | Required | Values and Description
    ---------------|----------|-----------------------
    `client_id`    | Required | The client id (aka key) from the couple key/secret provided by Flat
    `response_type`| Required | We support `code` (**Authorization Code** flow, [RFC6749/4.1.1](https://tools.ietf.org/html/rfc6749#section-4.1.1)) and `token`, [RFC6749/4.2.1](https://tools.ietf.org/html/rfc6749#section-4.2.1)). It is strongly advised to use the Authorization Code flow for any server-side usage and the Implicit flow for any client-side (e.g. JavaScript) usage.
    `scope`        | Required | You must provide a list of scopes listed above and granted for your app, separated with a space.
    `redirect_uri` | Required | Determines where the response is sent. The value of this parameter must exactly match the value specified in your App Credentials settings.
    `state`        | Optional | An opaque string that is round-tripped in the protocol; that is to say, it is returned as a URI parameter in the Basic flow, and in the URI #fragment in the Implicit flow.
    `access_type`  | Optional, only available for the Authorization Code flow | The acceptable values are `online` and `offline`. When specifying `offline`, the API will return a refresh token during the access token exchange.

    ### OAuth2 tokens revocation

    This OAuth2 API supports token revocation ([RFC 7009](http://tools.ietf.org/html/rfc7009)) at the following endpoint: `https://api.flat.io/oauth/invalidate_token`.

    # CORS
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/). And that allows cross-domain communication from the browser.
    All responses have a wildcard same-origin which makes them completely public and accessible to everyone, including any code on any site.

    # Rate Limiting
    For authenticated requests, you can make up to 5,000 requests per hour.
    For unauthenticated requests, the rate limit allows you to make up to 500 requests per hour. Unauthenticated requests are associated with your IP address, and not the user or app making requests.
    You can contact us if you need [extra quota](https://flat.io/developers).
    To protect our quality of service, additional rate limits may apply to some API calls or actions.

    You can check the returned HTTP headers of any API request to see your current rate limit status:
    ```bash
    curl -i https://api.flat.io/v2/me
    HTTP/1.1 200 OK
    Date: Sat, 25 Mar 2017 17:06:20 GMT
    X-RateLimit-Limit: 5000
    X-RateLimit-Remaining: 4999
    X-RateLimit-Reset: 1490465178
    ```

    The headers tell you everything you need to know about your current rate limit status:

    Header name | Description
    ------------|------------
    `X-RateLimit-Limit` | The maximum number of requests that the consumer is permitted to make per hour.
    `X-RateLimit-Remaining` | The number of requests remaining in the current rate limit window. This value can be negative if you try to go over the allowed quota.
    `X-RateLimit-Reset` | The time at which the current rate limit window resets in [UTC epoch seconds](http://en.wikipedia.org/wiki/Unix_time).

    If you need the time in a different format, any modern programming language can get the job done. For example, if you open up the console on your web browser, you can easily get the reset time as a JavaScript Date object.

    ```javascript
    new Date(1490465178 * 1000).toString()
    'Sat Mar 25 2017 19:06:18 GMT+0100 (CET)'
    ```

    Once you go over the rate limit you will receive an error response:
    ```bash
    curl -i https://api.flat.io/v2/me
    HTTP/1.1 403 Forbidden
    X-RateLimit-Limit: 5000
    X-RateLimit-Remaining: 0
    X-RateLimit-Reset: 1490465829

    {
      "message": "API rate limit exceeded for xx.xxx.xxx.xx",
      "code": "API_RATE_LIMIT_EXCEEDED"
    }
    ```
  version: 2.0.0
  termsOfService: https://flat.io/legal
  contact:
    name: Flat
    url: https://flat.io/support
    email: developers@flat.io
  x-logo:
    url: https://flat.io/img/logo-white.svg

host: api.flat.io
basePath: /v2
schemes:
- https
securityDefinitions:
  OAuth2:
    type: oauth2
    description: |
      OAuth 2.0 authentication for your app or. Please only request the most restrictive and needed scopes. Using some of the scopes may require an additional review from our team. The Flat API supports **authorization code** and **implicit** flows.
    authorizationUrl: https://flat.io/auth/oauth
    tokenUrl: https://api.flat.io/oauth/access_token
    flow: accessCode
    scopes:
      account.public_profile: |
        Provides access to the basic person's public profile. Education profiles may be anonymized with this scope, you can request the scope `education_profile` to access to the a basic education account profile.
      account.education_profile: |
        Provides access to the basic person's education profile and public organization information.
      scores.readonly: |
        Allows read-only access to all a user's scores. You won't need this scope to read public scores.
      scores.social: |
        Allow to post comments and like scores
      scores: |
        Full, permissive scope to access all of a user's scores.

tags:
- name: Account
  x-displayName: Flat Account
  description: |
    These API endpoints are related to the Flat account you are currently using. When using an OAuth2 access token, you can use [`GET /me`](#operation/getAuthenticatedUser) to get information about the account.
- name: Score
  x-displayName: Music scores
  description: |
    Sheet music is the main API object type available for all Flat account.

    Here is a typical lifecycle for a music score document on Flat:
      - An end user can **create a music score** or **import a document** using our [web interface](https://flat.io) or a third-party website/app (e.g. Google Drive) using this API (see [`POST /v2/scores`](#operation/createScore). The creation and import of music scores can be done with this single API endpoint. This one currently supports the [MusicXML](http://www.musicxml.com/) (compressed or not) and [MIDI](https://www.midi.org/specifications).
      - The scores from a single account can **be listed** with [`GET /users/{user}/scores`](#operation/getUserScores) as well of scores shared with a specific group with [`GET /groups/{group}/scores`](#operation/getGroupScores).
      - The metadata of a single score can be retrieved with [`GET /scores/{score}`](#operation/getScore).
      - Scores on Flat have **one or multiple revisions**: creating a new score will create a first revision. These **revisions can be listed** using [`GET /scores/{score}/revisions`](#operation/getScoreRevisions) and a specific **revision data can be downloaded** with [`GET /scores/{score}/revisions/{revision}/{format}`](#operation/getScoreRevisionData). New revisions can be created using our [sheet music editor](https://flat.io) or using [`POST /scores/{score}/revisions`](#operation/createScor[...]
      - Scores can be **shared publicly** by changing the privacy option with [`POST /scores/{score}`](#operation/editScore), or **individually shared** using the different collaborators API endpoints (see [`POST /scores/{score}/collaborators`](#operation/addScoreCollaborator)).
- name: User
  description: Flat users
paths:
  /me:
    get:
      tags: [Account]
      security:
      - OAuth2:
        - account.public_profile
        - account.education_profile
      summary: Get current user profile
      description: |
        Get details about the current authenticated User.
      operationId: getAuthenticatedUser
  /scores:
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Create a new score
      operationId: createScore
      description: |
        Use this API method to **create a new music score in the current User account**. You will need a MusicXML 3 (`vnd.recordare.musicxml` or `vnd.recordare.musicxml+xml`) or a MIDI (`audio/midi`) file to create the new Flat document.

        This API call will automatically create the first revision of the document, the score can be modified by the using our web application or by uploading a new revision of this file (`POST /v2/scores/{score}/revisions/{revision}`).

        The currently authenticated user will be granted owner of the file and will be able to add other collaborators (users and groups).
  /scores/{score}:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: Get a score's metadata
      description: |
        Get the details of a score identified by the `score` parameter in the URL.
        The currently authenticated user must have at least a read access to the document to use this API call.
      operationId: getScore
    put:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Edit a score's metadata
      description: |
        This API method allows you to change the metadata of a score document (e.g. its `title` or `privacy`), all the properties are optional.

        To edit the file itself, create a new revision using the appropriate method (`POST /v2/scores/{score}/revisions/{revision}`).
      operationId: editScore
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Delete a score
      description: |
        This API call will schedule the deletion of the score, its revisions, and whole history.
        The user calling this API method must have the `aclAdmin` rights on this document to process this action.
        The score won't be accessible anymore after calling this method and the user's quota will directly be updated.
      operationId: deleteScore
  /scores/{score}/fork:
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Fork a score
      description: |
        This API call will make a copy of the last revision of the specified score and create a new score. The copy of the score will have a privacy set to `private`.

        When using a [Flat for Education](https://flat.io/edu) account, the inline and contextualized comments will be accessible in the child document.
      operationId: forkScore
  /scores/{score}/collaborators:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores.readonly
        - scores
      summary: List the collaborators
      description: |
        This API call will list the different collaborators of a score and their rights on the document. The returned list will at least contain the owner of the document.

        Collaborators can be a single user (the object `user` will be populated) or a group (the object `group` will be populated).
      operationId: getScoreCollaborators
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores.readonly
        - scores
      summary: Add a new collaborator
      description: |
        Share a score with a single user or a group. This API call allows to add, invite and update the collaborators of a document.
        - To add an existing Flat user to the document, specify its unique identifier in the `user` property.
        - To invite an external user to the document, specify its email in the `userEmail` property.
        - To add a Flat group to the document, specify its unique identifier in the `group` property.
        - To update an existing collaborator, process the same request with different rights.
      operationId: addScoreCollaborator
  /scores/{score}/collaborators/{collaborator}:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores.readonly
        - scores
      summary: Get a collaborator
      description: |
        Get the information about a collaborator (User or Group).
      operationId: getScoreCollaborator
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Delete a collaborator
      description: |
        Remove the specified collaborator from the score
      operationId: removeScoreCollaborator
  /scores/{score}/comments:
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Post a new comment
      description: |
        Post a document or a contextualized comment on a document.

        Please note that this method includes an anti-spam system for public scores. We don't guarantee that your comments will be accepted and displayed to end-user. Comments are be blocked by returning a `403` HTTP error and hidden from other users when the `spam` property is `true`.
      operationId: postScoreComment
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores.readonly
        - scores.social
        - scores
      summary: List comments
      description: This method lists the different comments added on a music score (documents and inline) sorted by their post dates.
      operationId: getScoreComments
  /scores/{score}/comments/{comment}:
    put:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Update an existing comment
      operationId: updateScoreComment
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Delete a comment
      operationId: deleteScoreComment
  /scores/{score}/comments/{comment}/resolved:
    put:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Mark the comment as resolved
      operationId: markScoreCommentResolved
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Mark the comment as unresolved
      operationId: markScoreCommentUnresolved
  /scores/{score}/revisions:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: List the revisions
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to list all of them, sorted by last modification.

        Depending the plan of the account, this list can be trunked to the few last revisions.
      operationId: getScoreRevisions
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Create a new revision
      description: |
        Update a score by uploading a new revision for this one.
      operationId: createScoreRevision
  /scores/{score}/revisions/{revision}:
    get:
      tags: [Score]
      security: []
      summary: Get a score revision
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to get a specific
        revision metadata.
      operationId: getScoreRevision
  /scores/{score}/revisions/{revision}/{format}:
    get:
      tags: [Score]
      security: []
      summary: Get a score revision data
      description: |
        Retrieve the file corresponding to a score revision (the following formats are available: Flat JSON/Adagio JSON `json`, MusicXML
        `mxl`/`xml`, MP3 `mp3`, WAV `wav`, MIDI `midi`, or a tumbnail of the first page `thumbnail.png`).
      operationId: getScoreRevisionData
  /users/{user}:
    get:
      tags: [User]
      security:
      - OAuth2:
        - account.public_profile
        - account.education_profile
      summary: Get a public user profile
      description: |
        Get a public profile of a Flat User.
      operationId: getUser
  /users/{user}/likes:
    get:
      tags: [User, Score]
      security:
      - OAuth2:
        - account.public_profile
      summary: List liked scores
      operationId: gerUserLikes
  /users/{user}/scores:
    get:
      tags: [User, Score]
      security:
      - OAuth2:
        - scores.readonly
      summary: List user's scores
      description: |
        Get the list of scores owned by the User
      operationId: getUserScores
  /groups/{group}/scores:
    get:
      tags:
      - Group
      - Score
      security: []
      summary: List group's scores
      description: |
        Get the list of scores shared with a group.
      operationId: getGroupScores