# A Swagger 2.0 (a.k.a. OpenAPI) definition of the Flat API
#
# This is used for generating API documentation and the types used by the API clients.
#
# Some style notes:
# - This file is used by ReDoc, which allows GitHub Flavored Markdown in descriptions.
# - There is no maximum line length, for ease of editing and pretty diffs.

swagger: '2.0'

info:
  title: Flat API
  description: |
    The Flat API allows you to easily extend the abilities of the [Flat Platform](https://flat.io), with a wide range of use cases including the following:

    * Creating and importing new music scores using MusicXML or MIDI files
    * Browsing, updating, copying, exporting the user's scores (for example in MP3, WAV or MIDI)
    * Managing educational resources with Flat for Education: creating & updating the organization accounts, the classes, rosters and assignments.

    The Flat API is built on HTTP. Our API is RESTful It has predictable resource URLs. It returns HTTP response codes to indicate errors. It also accepts and returns JSON in the HTTP body.
    The [schema](/swagger.yaml) of this API follows the [OpenAPI Initiative (OAI) specification](https://www.openapis.org/), you can use and work with [compatible Swagger tools](http://swagger.io/open-source-integrations/).
    This API features Cross-Origin Resource Sharing (CORS) implemented in compliance with [W3C spec](https://www.w3.org/TR/cors/).

    You can use your favorite HTTP/REST library for your programming language to use Flat's API. This specification and reference is [available on Github](https://github.com/FlatIO/api-reference).

    Getting Started and learn more:

    * [API Overview and interoduction](https://flat.io/developers/docs/api/)
    * [Authentication (Personal Access Tokens or OAuth2)](https://flat.io/developers/docs/api/authentication.html)
    * [SDKs](https://flat.io/developers/docs/api/sdks.html)
    * [Rate Limits](https://flat.io/developers/docs/api/rate-limits.html)
    * [Changelog](https://flat.io/developers/docs/api/changelog.html)
  version: 2.5.1
  termsOfService: https://flat.io/legal
  contact:
    name: Flat
    url: https://flat.io/developers/docs/api/
    email: developers@flat.io
  x-logo:
    url: https://flat.io/img/logo-flat.svg

host: api.flat.io
basePath: /v2
schemes:
- https
securityDefinitions:
  OAuth2:
    type: oauth2
    description: |
      OAuth 2.0 authentication for your app or. Please only request the most restrictive and needed scopes. Using some of the scopes may require an additional review from our team. The Flat API supports **authorization code** and **implicit** flows.
    authorizationUrl: https://flat.io/auth/oauth
    tokenUrl: https://api.flat.io/oauth/access_token
    flow: accessCode
    scopes:
      account.public_profile: |
        Provides access to the basic person's public profile. Education profiles may be anonymized with this scope, you can request the scope `education_profile` to access to the a basic education account profile.
      account.education_profile: |
        Provides access to the basic person's education profile and public organization information.
      scores.readonly: |
        Allows read-only access to all a user's scores. You won't need this scope to read public scores.
      scores.social: |
        Allow to post comments and like scores
      scores: |
        Full, permissive scope to access all of a user's scores.
      edu.classes: Full, permissive scope to manage the classes.
      edu.classes.readonly: Read-only access to the classes.
      edu.assignments: Read-write access to the assignments and submissions.
      edu.assignments.readonly: Read-only access to the assignments and submissions.
      edu.admin: Full, permissive scope to manage all the admin of an organization.
      edu.admin.lti: Access and manage the LTI Credentials for an organization.
      edu.admin.lti.readonly: Read-only access to the LTI Credentials of an organization.
      edu.admin.users: Access and manage the users and invitations of the organization.
      edu.admin.users.readonly: Read-only access to the users and invitations of the organization.

tags:
- name: Account
  x-displayName: Flat Account
  description: |
    These API endpoints are related to the Flat account you are currently using. When using an OAuth2 access token, you can use [`GET /me`](#operation/getAuthenticatedUser) to get information about the account.
- name: Score
  x-displayName: Music scores
  description: |
    Sheet music is the main API object type available for all Flat account.

    Here is a typical lifecycle for a music score document on Flat:
      - An end user can **create a music score** or **import a document** using our [web interface](https://flat.io) or a third-party website/app (e.g. Google Drive) using this API (see [`POST /v2/scores`](#operation/createScore). The creation and import of music scores can be done with this single API endpoint. This one currently supports the [MusicXML](http://www.musicxml.com/) (compressed or not) and [MIDI](https://www.midi.org/specifications).
      - The scores from a single account can **be listed** with [`GET /users/{user}/scores`](#operation/getUserScores) as well of scores shared with a specific group with [`GET /groups/{group}/scores`](#operation/getGroupScores).
      - The metadata of a single score can be retrieved with [`GET /scores/{score}`](#operation/getScore).
      - Scores on Flat have **one or multiple revisions**: creating a new score will create a first revision. These **revisions can be listed** using [`GET /scores/{score}/revisions`](#operation/getScoreRevisions) and a specific **revision data can be downloaded** with [`GET /scores/{score}/revisions/{revision}/{format}`](#operation/getScoreRevisionData). New revisions can be created using our [sheet music editor](https://flat.io) or using [`POST /scores/{score}/revisions`](#operation/createScor[...]
      - Scores can be **shared publicly** by changing the privacy option with [`POST /scores/{score}`](#operation/editScore), or **individually shared** using the different collaborators API endpoints (see [`POST /scores/{score}/collaborators`](#operation/addScoreCollaborator)).
- name: User
  description: Flat users
- name: Organization
  description: Flat for Education organizations
- name: Class
  description: Flat for Education classes
- name: Group
  description: Flat Groups
paths:
  /me:
    get:
      tags: [Account]
      security:
      - OAuth2:
        - account.public_profile
        - account.education_profile
      summary: Get current user profile
      description: |
        Get details about the current authenticated User.
      operationId: getAuthenticatedUser
  /scores:
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Create a new score
      operationId: createScore
      description: |
        Use this API method to **create a new music score in the current User account**. You will need a MusicXML 3 (`vnd.recordare.musicxml` or `vnd.recordare.musicxml+xml`) or a MIDI (`audio/midi`) file to create the new Flat document.

        This API call will automatically create the first revision of the document, the score can be modified by the using our web application or by uploading a new revision of this file (`POST /v2/scores/{score}/revisions/{revision}`).

        The currently authenticated user will be granted owner of the file and will be able to add other collaborators (users and groups).
  /scores/{score}:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: Get a score's metadata
      description: |
        Get the details of a score identified by the `score` parameter in the URL.
        The currently authenticated user must have at least a read access to the document to use this API call.
      operationId: getScore
    put:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Edit a score's metadata
      description: |
        This API method allows you to change the metadata of a score document (e.g. its `title` or `privacy`), all the properties are optional.

        To edit the file itself, create a new revision using the appropriate method (`POST /v2/scores/{score}/revisions/{revision}`).
      operationId: editScore
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Delete a score
      description: |
        This API call will schedule the deletion of the score, its revisions, and whole history.
        The user calling this API method must have the `aclAdmin` rights on this document to process this action.
        The score won't be accessible anymore after calling this method and the user's quota will directly be updated.
      operationId: deleteScore
  /scores/{score}/submissions:
    get:
      tags: [Score, Class]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: List submissions related to the score
      description: |
        This API call will list the different assignments submissions where the score is attached. This method can be used by anyone that are part of the organization and have at least read access to the document.
      operationId: getScoreSubmissions
  /scores/{score}/fork:
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Fork a score
      description: |
        This API call will make a copy of the last revision of the specified score and create a new score. The copy of the score will have a privacy set to `private`.

        When using a [Flat for Education](https://flat.io/edu) account, the inline and contextualized comments will be accessible in the child document.
      operationId: forkScore
  /scores/{score}/collaborators:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores.readonly
        - scores
      summary: List the collaborators
      description: |
        This API call will list the different collaborators of a score and their rights on the document. The returned list will at least contain the owner of the document.

        Collaborators can be a single user (the object `user` will be populated) or a group (the object `group` will be populated).
      operationId: getScoreCollaborators
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Add a new collaborator
      description: |
        Share a score with a single user or a group. This API call allows to add, invite and update the collaborators of a document.
        - To add an existing Flat user to the document, specify its unique identifier in the `user` property.
        - To invite an external user to the document, specify its email in the `userEmail` property.
        - To add a Flat group to the document, specify its unique identifier in the `group` property.
        - To update an existing collaborator, process the same request with different rights.
      operationId: addScoreCollaborator
  /scores/{score}/collaborators/{collaborator}:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores.readonly
      summary: Get a collaborator
      description: |
        Get the information about a collaborator (User or Group).
      operationId: getScoreCollaborator
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Delete a collaborator
      description: |
        Remove the specified collaborator from the score
      operationId: removeScoreCollaborator
  /scores/{score}/tracks:
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Add a new video or audio track to the score
      description: |
        Use this method to add new track to the score. This track can then be played on flat.io or in an embedded score.
        This API method support medias hosted on SoundCloud, YouTube and Vimeo.
      operationId: addScoreTrack
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: List the audio or video tracks linked to a score
      operationId: listScoreTracks
  /scores/{score}/tracks/{track}:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: Retrieve the details of an audio or video track linked to a score
      operationId: getScoreTrack
    put:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Update an audio or video track linked to a score
      operationId: updateScoreTrack
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Remove an audio or video track linked to the score
      operationId: deleteScoreTrack
  /scores/{score}/comments:
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Post a new comment
      description: |
        Post a document or a contextualized comment on a document.

        Please note that this method includes an anti-spam system for public scores. We don't guarantee that your comments will be accepted and displayed to end-user. Comments are be blocked by returning a `403` HTTP error and hidden from other users when the `spam` property is `true`.
      operationId: postScoreComment
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores.readonly
        - scores.social
        - scores
      summary: List comments
      description: This method lists the different comments added on a music score (documents and inline) sorted by their post dates.
      operationId: getScoreComments
  /scores/{score}/comments/{comment}:
    put:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Update an existing comment
      operationId: updateScoreComment
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Delete a comment
      operationId: deleteScoreComment
  /scores/{score}/comments/{comment}/resolved:
    put:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Mark the comment as resolved
      operationId: markScoreCommentResolved
    delete:
      tags: [Score]
      security:
      - OAuth2:
        - scores.social
        - scores
      summary: Mark the comment as unresolved
      operationId: markScoreCommentUnresolved
  /scores/{score}/revisions:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: List the revisions
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to list all of them, sorted by last modification.

        Depending the plan of the account, this list can be trunked to the few last revisions.
      operationId: getScoreRevisions
    post:
      tags: [Score]
      security:
      - OAuth2:
        - scores
      summary: Create a new revision
      description: |
        Update a score by uploading a new revision for this one.
      operationId: createScoreRevision
  /scores/{score}/revisions/{revision}:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: Get a score revision
      description: |
        When creating a score or saving a new version of a score, a revision is created in our storage. This method allows you to get a specific
        revision metadata.
      operationId: getScoreRevision
  /scores/{score}/revisions/{revision}/{format}:
    get:
      tags: [Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: Get a score revision data
      description: |
        Retrieve the file corresponding to a score revision (the following formats are available: Flat JSON/Adagio JSON `json`, MusicXML
        `mxl`/`xml`, MP3 `mp3`, WAV `wav`, MIDI `midi`, or a tumbnail of the first page `thumbnail.png`).
      operationId: getScoreRevisionData
  /users/{user}:
    get:
      tags: [User]
      security:
      - OAuth2:
        - account.public_profile
        - account.education_profile
      summary: Get a public user profile
      description: |
        Get a public profile of a Flat User.
      operationId: getUser
  /users/{user}/likes:
    get:
      tags: [User, Score]
      security:
      - OAuth2:
        - account.public_profile
      summary: List liked scores
      operationId: gerUserLikes
  /users/{user}/scores:
    get:
      tags: [User, Score]
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: List user's scores
      description: |
        Get the list of scores owned by the User
      operationId: getUserScores
  /organizations/users:
    post:
      tags: [Organization]
      summary: Create a new user account
      operationId: createOrganizationUser
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
    get:
      tags: [Organization]
      summary: List the organization users
      operationId: listOrganizationUsers
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
  /organizations/users/{user}:
    put:
      tags: [Organization]
      summary: Update account information
      operationId: updateOrganizationUser
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
    delete:
      tags: [Organization]
      summary: Remove an account from Flat
      description: |
        This operation removes an account from Flat and its data, including:
        * The music scores created by this user (documents, history, comments, collaboration information)
        * Education related data (assignments and classroom information)
      operationId: removeOrganizationUser
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/invitations:
    post:
      tags: [Organization]
      summary: Create a new invitation to join the organization
      description: |
        This method creates and sends invitation for teachers and admins.

        Invitations can only be used by new Flat users or users who are not part of the organization yet.

        If the email of the user is already associated to a user of your organization, the API will simply update the role of the existing user and won't send an invitation. In this case, the property `usedBy` will be directly filled with the uniquer identifier of the corresponding user.
      operationId: createOrganizationInvitation
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
    get:
      tags: [Organization]
      summary: List the organization invitations
      operationId: listOrganizationInvitations
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
  /organizations/invitations/{invitation}:
    delete:
      tags: [Organization]
      summary: Remove an organization invitation
      operationId: removeOrganizationInvitation
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
  /organizations/lti/credentials:
    post:
      tags: [Organization]
      summary: Create a new couple of LTI 1.x credentials
      description: |
        Flat for Education is a Certified LTI Provider. You can use these API methods to automate the creation of LTI credentials. You can read more about our LTI implementation, supported components and LTI Endpoints in our [Developer Documentation](https://flat.io/developers/docs/lti/).
      operationId: createLtiCredentials
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.lti
    get:
      tags: [Organization]
      summary: List LTI 1.x credentials
      operationId: listLtiCredentials
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.lti
        - edu.admin.lti.readonly
  /organizations/lti/credentials/{credentials}:
    delete:
      tags: [Organization]
      summary: Revoke LTI 1.x credentials
      operationId: revokeLtiCredentials
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.lti
  /classes:
    post:
      tags: [Class]
      summary: Create a new class
      description: |
        Classrooms on Flat allow you to create activities with assignments and post content to a specific group.

        When creating a class, Flat automatically creates two groups: one for the teachers of the course, one for the students. The creator of this class is automatically added to the teachers group.

        If the classsroom is synchronized with another application like Google Classroom, some of the meta information will automatically be updated.

        You can add users to this class using `POST /classes/{class}/users/{user}`, they will automatically added to the group based on their role on Flat. Users can also enroll themselves to this class using `POST /classes/enroll/{enrollmentCode}` and the `enrollmentCode` returned in the `ClassDetails` response.
      operationId: createClass
      security:
      - OAuth2:
        - edu.classes
    get:
      tags: [Class]
      summary: List the classes available for the current user
      operationId: listClasses
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
  /classes/{class}:
    get:
      tags: [Class]
      summary: Get the details of a single class
      operationId: getClass
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
    put:
      tags: [Class]
      summary: Update the class
      description: |
        Update the meta information of the class
      operationId: updateClass
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/archive:
    post:
      tags: [Class]
      summary: Archive the class
      operationId: archiveClass
      description: |
        Mark the class as `archived`. When this course is synchronized with another app, like Google Classroom, this state will be automatically be updated.
      security:
      - OAuth2:
        - edu.classes
    delete:
      tags: [Class]
      summary: Unarchive the class
      description: |
        Mark the class as `active`. When this course is synchronized with another app, like Google Classroom, this state will be automatically be updated.
      operationId: unarchiveClass
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/activate:
    post:
      tags: [Class]
      summary: Activate the class
      operationId: activateClass
      description: |
        Mark the class as `active`. This is mainly used for classes synchronized from Clever that are initially with an `inactive` state and hidden in the UI.
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/users/{user}:
    put:
      tags: [Class]
      summary: Add a user to the class
      description: |
        This method can be used by a teacher of the class to enroll another Flat user into the class.

        Only users that are part of your Organization can be enrolled in a class of this same Organization.

        When enrolling a user in the class, Flat will automatically add this user to the corresponding Class group, based on this role in the Organization.
      operationId: addClassUser
      security:
      - OAuth2:
        - edu.classes
    delete:
      tags: [Class]
      summary: Remove a user from the class
      operationId: deleteClassUser
      description: |
        This method can be used by a teacher to remove a user from the class, or by a student to leave the classroom.

        Warning: Removing a user from the class will remove the associated resources, including the submissions and feedback related to these submissions.
      security:
      - OAuth2:
        - edu.classes
  /classes/{class}/students/{user}/submissions:
    get:
      tags: [Class]
      summary: List the submissions for a student
      description: |
        Use this method as a teacher to list all the assignment submissions sent by a student of the class
      operationId: listClassStudentSubmissions
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
  /classes/{class}/assignments:
    post:
      tags: [Class]
      summary: Assignment creation
      operationId: createAssignment
      description: |
        Use this method as a teacher to create and post a new assignment to a class.

        If the class is synchronized with Google Classroom, the assignment will be automatically posted to your Classroom course.
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
    get:
      tags: [Class]
      summary: Assignments listing
      operationId: listAssignments
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
  /classes/{class}/assignments/{assignment}/copy:
    post:
      tags: [Class]
      summary: Copy an assignment
      description: |
        Copy an assignment to a specified class.

        If the original assignment has a due date in the past, this new assingment will be created without a due date.

        If the new class is synchronized with an external app (e.g. Google Classroom), the copied assignment will also be posted on the external app.
      operationId: copyAssignment
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
  /classes/{class}/assignments/{assignment}/submissions:
    put:
      tags: [Class]
      summary: Create or edit a submission
      description: |
        Use this method as a student to create, update and submit a submission related to an assignment. Students can only set `attachments`, `studentComment` and `submit`.

        Teachers can use `PUT /classes/{class}/assignments/{assignment}/submissions/{submission}` to update a submission by id.
      operationId: createSubmission
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
    get:
      tags: [Class]
      summary: List the students' submissions
      operationId: getSubmissions
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
  /classes/{class}/assignments/{assignment}/submissions/{submission}:
    put:
      tags: [Class]
      summary: Edit a submission
      description: |
        Use this method as a teacher to update the different submission and give feedback.
        Teachers can only set `returnFeedback`
      operationId: editSubmission
      security:
      - OAuth2:
        - edu.classes
        - edu.assignments
    get:
      tags: [Class]
      summary: Get a student submission
      operationId: getSubmission
      security:
      - OAuth2:
        - edu.classes
        - edu.classes.readonly
        - edu.assignments
        - edu.assignments.readonly
  /classes/enroll/{enrollmentCode}:
    post:
      tags: [Class]
      summary: Join a class
      description: |
        Use this method to join a class using an enrollment code given one of the teacher of this class. This code is also available in the `ClassDetails` returned to the teachers when creating the class or listing / fetching a specific class.

        Flat will automatically add the user to the corresponding class group based on this role in the organization.
      operationId: enrollClass
      security:
      - OAuth2:
        - edu.classes
  /groups/{group}:
    get:
      tags:
      - Group
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
        - edu.classes
        - edu.classes.readonly
      summary: Get group information
      operationId: getGroupDetails
  /groups/{group}/users:
    get:
      tags:
      - Group
      security:
      - OAuth2:
        - edu.admin
        - edu.admin.users
        - edu.admin.users.readonly
        - edu.classes
        - edu.classes.readonly
      summary: List group's users
      operationId: listGroupUsers
  /groups/{group}/scores:
    get:
      tags:
      - Group
      - Score
      security:
      - OAuth2:
        - scores
        - scores.readonly
      summary: List group's scores
      description: |
        Get the list of scores shared with a group.
      operationId: getGroupScores